name= input("what is your name: ")
surname = input("what is your surname: ")
print("so you are: "+ surname + name)
age = input("what is your age: ")
print("your age is: " + age)
city = input("what city do you live in: ")
print("you live in: " + city)
school = ("where do you study: ")
print("this is where you study: " + school)
